// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: remote_manage.proto

// SPDX-License-Identifier: GPL-3.0-or-later
//
// Frameo remote-manage subset, hand-corrected from frameo_full.proto (which was
// machine-generated from a jadx decompile and emitted repeated message fields as
// "repeated int32" and cross-file message refs as "bytes" -- both wire-incompatible).
// Field numbers are authoritative (*_FIELD_NUMBER constants). The repeated-scalar
// subtype of mediaIds is MEDIUM confidence: sint64 here, matching MediaMetaData.mediaId.
// Verify against a live frame before trusting delete/visibility.

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaMetaData_Type int32

const (
	MediaMetaData_Type_MEDIAMETADATA_TYPE_PICTURE  MediaMetaData_Type = 0
	MediaMetaData_Type_MEDIAMETADATA_TYPE_VIDEO    MediaMetaData_Type = 1
	MediaMetaData_Type_MEDIAMETADATA_TYPE_GREETING MediaMetaData_Type = 2
)

// Enum value maps for MediaMetaData_Type.
var (
	MediaMetaData_Type_name = map[int32]string{
		0: "MEDIAMETADATA_TYPE_PICTURE",
		1: "MEDIAMETADATA_TYPE_VIDEO",
		2: "MEDIAMETADATA_TYPE_GREETING",
	}
	MediaMetaData_Type_value = map[string]int32{
		"MEDIAMETADATA_TYPE_PICTURE":  0,
		"MEDIAMETADATA_TYPE_VIDEO":    1,
		"MEDIAMETADATA_TYPE_GREETING": 2,
	}
)

func (x MediaMetaData_Type) Enum() *MediaMetaData_Type {
	p := new(MediaMetaData_Type)
	*p = x
	return p
}

func (x MediaMetaData_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaMetaData_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_remote_manage_proto_enumTypes[0].Descriptor()
}

func (MediaMetaData_Type) Type() protoreflect.EnumType {
	return &file_remote_manage_proto_enumTypes[0]
}

func (x MediaMetaData_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaMetaData_Type.Descriptor instead.
func (MediaMetaData_Type) EnumDescriptor() ([]byte, []int) {
	return file_remote_manage_proto_rawDescGZIP(), []int{0}
}

type MediaMetaData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       int64                  `protobuf:"zigzag64,1,opt,name=mediaId,proto3" json:"mediaId,omitempty"`
	Type          MediaMetaData_Type     `protobuf:"varint,2,opt,name=type,proto3,enum=frameo.MediaMetaData_Type" json:"type,omitempty"`
	IsVisible     bool                   `protobuf:"varint,3,opt,name=isVisible,proto3" json:"isVisible,omitempty"`
	CaptureDate   int64                  `protobuf:"zigzag64,4,opt,name=captureDate,proto3" json:"captureDate,omitempty"`
	ReceiveDate   int64                  `protobuf:"zigzag64,5,opt,name=receiveDate,proto3" json:"receiveDate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaMetaData) Reset() {
	*x = MediaMetaData{}
	mi := &file_remote_manage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaMetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaMetaData) ProtoMessage() {}

func (x *MediaMetaData) ProtoReflect() protoreflect.Message {
	mi := &file_remote_manage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaMetaData.ProtoReflect.Descriptor instead.
func (*MediaMetaData) Descriptor() ([]byte, []int) {
	return file_remote_manage_proto_rawDescGZIP(), []int{0}
}

func (x *MediaMetaData) GetMediaId() int64 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

func (x *MediaMetaData) GetType() MediaMetaData_Type {
	if x != nil {
		return x.Type
	}
	return MediaMetaData_Type_MEDIAMETADATA_TYPE_PICTURE
}

func (x *MediaMetaData) GetIsVisible() bool {
	if x != nil {
		return x.IsVisible
	}
	return false
}

func (x *MediaMetaData) GetCaptureDate() int64 {
	if x != nil {
		return x.CaptureDate
	}
	return 0
}

func (x *MediaMetaData) GetReceiveDate() int64 {
	if x != nil {
		return x.ReceiveDate
	}
	return 0
}

type GetAllMediaMetaData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllMediaMetaData) Reset() {
	*x = GetAllMediaMetaData{}
	mi := &file_remote_manage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllMediaMetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMediaMetaData) ProtoMessage() {}

func (x *GetAllMediaMetaData) ProtoReflect() protoreflect.Message {
	mi := &file_remote_manage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMediaMetaData.ProtoReflect.Descriptor instead.
func (*GetAllMediaMetaData) Descriptor() ([]byte, []int) {
	return file_remote_manage_proto_rawDescGZIP(), []int{1}
}

type AllMediaMetaData struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MediaMetaDataItems []*MediaMetaData       `protobuf:"bytes,1,rep,name=mediaMetaDataItems,proto3" json:"mediaMetaDataItems,omitempty"`
	Error              *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AllMediaMetaData) Reset() {
	*x = AllMediaMetaData{}
	mi := &file_remote_manage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllMediaMetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllMediaMetaData) ProtoMessage() {}

func (x *AllMediaMetaData) ProtoReflect() protoreflect.Message {
	mi := &file_remote_manage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllMediaMetaData.ProtoReflect.Descriptor instead.
func (*AllMediaMetaData) Descriptor() ([]byte, []int) {
	return file_remote_manage_proto_rawDescGZIP(), []int{2}
}

func (x *AllMediaMetaData) GetMediaMetaDataItems() []*MediaMetaData {
	if x != nil {
		return x.MediaMetaDataItems
	}
	return nil
}

func (x *AllMediaMetaData) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type DeleteMedia struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	MediaIds                     []int64                `protobuf:"zigzag64,1,rep,packed,name=mediaIds,proto3" json:"mediaIds,omitempty"`
	RequiresAcknowledgeReceiptId int64                  `protobuf:"varint,16,opt,name=requiresAcknowledgeReceiptId,proto3" json:"requiresAcknowledgeReceiptId,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *DeleteMedia) Reset() {
	*x = DeleteMedia{}
	mi := &file_remote_manage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMedia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMedia) ProtoMessage() {}

func (x *DeleteMedia) ProtoReflect() protoreflect.Message {
	mi := &file_remote_manage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMedia.ProtoReflect.Descriptor instead.
func (*DeleteMedia) Descriptor() ([]byte, []int) {
	return file_remote_manage_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteMedia) GetMediaIds() []int64 {
	if x != nil {
		return x.MediaIds
	}
	return nil
}

func (x *DeleteMedia) GetRequiresAcknowledgeReceiptId() int64 {
	if x != nil {
		return x.RequiresAcknowledgeReceiptId
	}
	return 0
}

type ChangeMediaVisibility struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	MediaIds                     []int64                `protobuf:"zigzag64,1,rep,packed,name=mediaIds,proto3" json:"mediaIds,omitempty"`
	IsVisible                    bool                   `protobuf:"varint,2,opt,name=isVisible,proto3" json:"isVisible,omitempty"`
	RequiresAcknowledgeReceiptId int64                  `protobuf:"varint,16,opt,name=requiresAcknowledgeReceiptId,proto3" json:"requiresAcknowledgeReceiptId,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *ChangeMediaVisibility) Reset() {
	*x = ChangeMediaVisibility{}
	mi := &file_remote_manage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeMediaVisibility) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeMediaVisibility) ProtoMessage() {}

func (x *ChangeMediaVisibility) ProtoReflect() protoreflect.Message {
	mi := &file_remote_manage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeMediaVisibility.ProtoReflect.Descriptor instead.
func (*ChangeMediaVisibility) Descriptor() ([]byte, []int) {
	return file_remote_manage_proto_rawDescGZIP(), []int{4}
}

func (x *ChangeMediaVisibility) GetMediaIds() []int64 {
	if x != nil {
		return x.MediaIds
	}
	return nil
}

func (x *ChangeMediaVisibility) GetIsVisible() bool {
	if x != nil {
		return x.IsVisible
	}
	return false
}

func (x *ChangeMediaVisibility) GetRequiresAcknowledgeReceiptId() int64 {
	if x != nil {
		return x.RequiresAcknowledgeReceiptId
	}
	return 0
}

var File_remote_manage_proto protoreflect.FileDescriptor

const file_remote_manage_proto_rawDesc = "" +
	"\n" +
	"\x13remote_manage.proto\x12\x06frameo\x1a\fframeo.proto\"\xbb\x01\n" +
	"\rMediaMetaData\x12\x18\n" +
	"\amediaId\x18\x01 \x01(\x12R\amediaId\x12.\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1a.frameo.MediaMetaData_TypeR\x04type\x12\x1c\n" +
	"\tisVisible\x18\x03 \x01(\bR\tisVisible\x12 \n" +
	"\vcaptureDate\x18\x04 \x01(\x12R\vcaptureDate\x12 \n" +
	"\vreceiveDate\x18\x05 \x01(\x12R\vreceiveDate\"\x15\n" +
	"\x13GetAllMediaMetaData\"~\n" +
	"\x10AllMediaMetaData\x12E\n" +
	"\x12mediaMetaDataItems\x18\x01 \x03(\v2\x15.frameo.MediaMetaDataR\x12mediaMetaDataItems\x12#\n" +
	"\x05error\x18\x02 \x01(\v2\r.frameo.ErrorR\x05error\"m\n" +
	"\vDeleteMedia\x12\x1a\n" +
	"\bmediaIds\x18\x01 \x03(\x12R\bmediaIds\x12B\n" +
	"\x1crequiresAcknowledgeReceiptId\x18\x10 \x01(\x03R\x1crequiresAcknowledgeReceiptId\"\x95\x01\n" +
	"\x15ChangeMediaVisibility\x12\x1a\n" +
	"\bmediaIds\x18\x01 \x03(\x12R\bmediaIds\x12\x1c\n" +
	"\tisVisible\x18\x02 \x01(\bR\tisVisible\x12B\n" +
	"\x1crequiresAcknowledgeReceiptId\x18\x10 \x01(\x03R\x1crequiresAcknowledgeReceiptId*s\n" +
	"\x12MediaMetaData_Type\x12\x1e\n" +
	"\x1aMEDIAMETADATA_TYPE_PICTURE\x10\x00\x12\x1c\n" +
	"\x18MEDIAMETADATA_TYPE_VIDEO\x10\x01\x12\x1f\n" +
	"\x1bMEDIAMETADATA_TYPE_GREETING\x10\x02B.Z,github.com/borje/unframeo/internal/frameo/pbb\x06proto3"

var (
	file_remote_manage_proto_rawDescOnce sync.Once
	file_remote_manage_proto_rawDescData []byte
)

func file_remote_manage_proto_rawDescGZIP() []byte {
	file_remote_manage_proto_rawDescOnce.Do(func() {
		file_remote_manage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_remote_manage_proto_rawDesc), len(file_remote_manage_proto_rawDesc)))
	})
	return file_remote_manage_proto_rawDescData
}

var file_remote_manage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_remote_manage_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_remote_manage_proto_goTypes = []any{
	(MediaMetaData_Type)(0),       // 0: frameo.MediaMetaData_Type
	(*MediaMetaData)(nil),         // 1: frameo.MediaMetaData
	(*GetAllMediaMetaData)(nil),   // 2: frameo.GetAllMediaMetaData
	(*AllMediaMetaData)(nil),      // 3: frameo.AllMediaMetaData
	(*DeleteMedia)(nil),           // 4: frameo.DeleteMedia
	(*ChangeMediaVisibility)(nil), // 5: frameo.ChangeMediaVisibility
	(*Error)(nil),                 // 6: frameo.Error
}
var file_remote_manage_proto_depIdxs = []int32{
	0, // 0: frameo.MediaMetaData.type:type_name -> frameo.MediaMetaData_Type
	1, // 1: frameo.AllMediaMetaData.mediaMetaDataItems:type_name -> frameo.MediaMetaData
	6, // 2: frameo.AllMediaMetaData.error:type_name -> frameo.Error
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_remote_manage_proto_init() }
func file_remote_manage_proto_init() {
	if File_remote_manage_proto != nil {
		return
	}
	file_frameo_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_remote_manage_proto_rawDesc), len(file_remote_manage_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_remote_manage_proto_goTypes,
		DependencyIndexes: file_remote_manage_proto_depIdxs,
		EnumInfos:         file_remote_manage_proto_enumTypes,
		MessageInfos:      file_remote_manage_proto_msgTypes,
	}.Build()
	File_remote_manage_proto = out.File
	file_remote_manage_proto_goTypes = nil
	file_remote_manage_proto_depIdxs = nil
}
