// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: control.proto

// SPDX-License-Identifier: GPL-3.0-or-later
//
// SecureDeviceGrid control-channel messages, matching the control protocol of
// the opensdg C library (https://github.com/Sonic-Amiga/opensdg), GPLv3.

package control

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MSG_FORWARD_REMOTE
type ForwardRemote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Magic         *uint32                `protobuf:"fixed32,1,req,name=magic" json:"magic,omitempty"`                // FORWARD_REMOTE_MAGIC
	ProtocolMajor *uint32                `protobuf:"varint,2,req,name=protocolMajor" json:"protocolMajor,omitempty"` // Protocol version
	ProtocolMinor *uint32                `protobuf:"varint,3,req,name=protocolMinor" json:"protocolMinor,omitempty"`
	TunnelId      []byte                 `protobuf:"bytes,4,req,name=tunnelId" json:"tunnelId,omitempty"`   // Tunnel ID from MSG_REMOTE_REPLY
	Signature     *string                `protobuf:"bytes,5,req,name=signature" json:"signature,omitempty"` // "Mdg-NaCl/binary"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardRemote) Reset() {
	*x = ForwardRemote{}
	mi := &file_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardRemote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardRemote) ProtoMessage() {}

func (x *ForwardRemote) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardRemote.ProtoReflect.Descriptor instead.
func (*ForwardRemote) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

func (x *ForwardRemote) GetMagic() uint32 {
	if x != nil && x.Magic != nil {
		return *x.Magic
	}
	return 0
}

func (x *ForwardRemote) GetProtocolMajor() uint32 {
	if x != nil && x.ProtocolMajor != nil {
		return *x.ProtocolMajor
	}
	return 0
}

func (x *ForwardRemote) GetProtocolMinor() uint32 {
	if x != nil && x.ProtocolMinor != nil {
		return *x.ProtocolMinor
	}
	return 0
}

func (x *ForwardRemote) GetTunnelId() []byte {
	if x != nil {
		return x.TunnelId
	}
	return nil
}

func (x *ForwardRemote) GetSignature() string {
	if x != nil && x.Signature != nil {
		return *x.Signature
	}
	return ""
}

// MSG_PROTOCOL_VERSION
type Property struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *string                `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value         *string                `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Property) Reset() {
	*x = Property{}
	mi := &file_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Property) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Property) ProtoMessage() {}

func (x *Property) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Property.ProtoReflect.Descriptor instead.
func (*Property) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

func (x *Property) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *Property) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type ProtocolVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Magic         *uint32                `protobuf:"fixed32,1,req,name=magic" json:"magic,omitempty"`
	Major         *uint32                `protobuf:"varint,2,req,name=major" json:"major,omitempty"`
	Minor         *uint32                `protobuf:"varint,3,req,name=minor" json:"minor,omitempty"`
	Properties    []*Property            `protobuf:"bytes,4,rep,name=properties" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolVersion) Reset() {
	*x = ProtocolVersion{}
	mi := &file_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolVersion) ProtoMessage() {}

func (x *ProtocolVersion) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolVersion.ProtoReflect.Descriptor instead.
func (*ProtocolVersion) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

func (x *ProtocolVersion) GetMagic() uint32 {
	if x != nil && x.Magic != nil {
		return *x.Magic
	}
	return 0
}

func (x *ProtocolVersion) GetMajor() uint32 {
	if x != nil && x.Major != nil {
		return *x.Major
	}
	return 0
}

func (x *ProtocolVersion) GetMinor() uint32 {
	if x != nil && x.Minor != nil {
		return *x.Minor
	}
	return 0
}

func (x *ProtocolVersion) GetProperties() []*Property {
	if x != nil {
		return x.Properties
	}
	return nil
}

// MSG_PING
type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           *uint32                `protobuf:"varint,1,req,name=seq" json:"seq,omitempty"`
	Delay         *uint32                `protobuf:"varint,2,opt,name=delay" json:"delay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{3}
}

func (x *Ping) GetSeq() uint32 {
	if x != nil && x.Seq != nil {
		return *x.Seq
	}
	return 0
}

func (x *Ping) GetDelay() uint32 {
	if x != nil && x.Delay != nil {
		return *x.Delay
	}
	return 0
}

// MSG_PONG
type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           *uint32                `protobuf:"varint,1,req,name=seq" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{4}
}

func (x *Pong) GetSeq() uint32 {
	if x != nil && x.Seq != nil {
		return *x.Seq
	}
	return 0
}

// MSG_FORWARD_REPLY
type ForwardReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     *string                `protobuf:"bytes,1,req,name=signature" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardReply) Reset() {
	*x = ForwardReply{}
	mi := &file_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardReply) ProtoMessage() {}

func (x *ForwardReply) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardReply.ProtoReflect.Descriptor instead.
func (*ForwardReply) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{5}
}

func (x *ForwardReply) GetSignature() string {
	if x != nil && x.Signature != nil {
		return *x.Signature
	}
	return ""
}

// MSG_FORWARD_ERROR
type ForwardError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          *uint32                `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardError) Reset() {
	*x = ForwardError{}
	mi := &file_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardError) ProtoMessage() {}

func (x *ForwardError) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardError.ProtoReflect.Descriptor instead.
func (*ForwardError) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{6}
}

func (x *ForwardError) GetCode() uint32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

// MSG_CALL_REMOTE
type ConnectToPeer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	PeerId        *string                `protobuf:"bytes,2,req,name=peerId" json:"peerId,omitempty"`
	Protocol      *string                `protobuf:"bytes,3,req,name=protocol" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectToPeer) Reset() {
	*x = ConnectToPeer{}
	mi := &file_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectToPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectToPeer) ProtoMessage() {}

func (x *ConnectToPeer) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectToPeer.ProtoReflect.Descriptor instead.
func (*ConnectToPeer) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{7}
}

func (x *ConnectToPeer) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *ConnectToPeer) GetPeerId() string {
	if x != nil && x.PeerId != nil {
		return *x.PeerId
	}
	return ""
}

func (x *ConnectToPeer) GetProtocol() string {
	if x != nil && x.Protocol != nil {
		return *x.Protocol
	}
	return ""
}

// MSG_REMOTE_REPLY, MSG_PAIR_REMOTE_REPLY
type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        *string                `protobuf:"bytes,3,req,name=peerId" json:"peerId,omitempty"`
	Server        *PeerInfo_ForwardHost  `protobuf:"bytes,4,req,name=server" json:"server,omitempty"`
	TunnelId      []byte                 `protobuf:"bytes,5,req,name=tunnelId" json:"tunnelId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{8}
}

func (x *PeerInfo) GetPeerId() string {
	if x != nil && x.PeerId != nil {
		return *x.PeerId
	}
	return ""
}

func (x *PeerInfo) GetServer() *PeerInfo_ForwardHost {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *PeerInfo) GetTunnelId() []byte {
	if x != nil {
		return x.TunnelId
	}
	return nil
}

type PeerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Result        *uint32                `protobuf:"varint,2,req,name=result" json:"result,omitempty"` // 0 = OK, 1 = refuse
	Peer          *PeerInfo              `protobuf:"bytes,3,opt,name=peer" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerReply) Reset() {
	*x = PeerReply{}
	mi := &file_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerReply) ProtoMessage() {}

func (x *PeerReply) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerReply.ProtoReflect.Descriptor instead.
func (*PeerReply) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{9}
}

func (x *PeerReply) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *PeerReply) GetResult() uint32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

func (x *PeerReply) GetPeer() *PeerInfo {
	if x != nil {
		return x.Peer
	}
	return nil
}

// MSG_INCOMING_CALL
type IncomingCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Peer          *PeerInfo              `protobuf:"bytes,2,req,name=peer" json:"peer,omitempty"`
	Protocol      *string                `protobuf:"bytes,3,req,name=protocol" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncomingCall) Reset() {
	*x = IncomingCall{}
	mi := &file_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncomingCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomingCall) ProtoMessage() {}

func (x *IncomingCall) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomingCall.ProtoReflect.Descriptor instead.
func (*IncomingCall) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{10}
}

func (x *IncomingCall) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *IncomingCall) GetPeer() *PeerInfo {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *IncomingCall) GetProtocol() string {
	if x != nil && x.Protocol != nil {
		return *x.Protocol
	}
	return ""
}

// MSG_INCOMING_CALL_REPLY
type IncomingCallReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Result        *uint32                `protobuf:"varint,2,req,name=result" json:"result,omitempty"` // 1 = accept; 0 = refuse
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncomingCallReply) Reset() {
	*x = IncomingCallReply{}
	mi := &file_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncomingCallReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomingCallReply) ProtoMessage() {}

func (x *IncomingCallReply) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomingCallReply.ProtoReflect.Descriptor instead.
func (*IncomingCallReply) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{11}
}

func (x *IncomingCallReply) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *IncomingCallReply) GetResult() uint32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

// MSG_PAIR_REMOTE
type PairRemote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Otp           *string                `protobuf:"bytes,2,req,name=otp" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairRemote) Reset() {
	*x = PairRemote{}
	mi := &file_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairRemote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairRemote) ProtoMessage() {}

func (x *PairRemote) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairRemote.ProtoReflect.Descriptor instead.
func (*PairRemote) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{12}
}

func (x *PairRemote) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *PairRemote) GetOtp() string {
	if x != nil && x.Otp != nil {
		return *x.Otp
	}
	return ""
}

type PeerInfo_ForwardHost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          *string                `protobuf:"bytes,1,req,name=host" json:"host,omitempty"`
	Port          *uint32                `protobuf:"varint,2,req,name=port" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo_ForwardHost) Reset() {
	*x = PeerInfo_ForwardHost{}
	mi := &file_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo_ForwardHost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo_ForwardHost) ProtoMessage() {}

func (x *PeerInfo_ForwardHost) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo_ForwardHost.ProtoReflect.Descriptor instead.
func (*PeerInfo_ForwardHost) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{8, 0}
}

func (x *PeerInfo_ForwardHost) GetHost() string {
	if x != nil && x.Host != nil {
		return *x.Host
	}
	return ""
}

func (x *PeerInfo_ForwardHost) GetPort() uint32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\n" +
	"sdgcontrol\"\xab\x01\n" +
	"\rForwardRemote\x12\x14\n" +
	"\x05magic\x18\x01 \x02(\aR\x05magic\x12$\n" +
	"\rprotocolMajor\x18\x02 \x02(\rR\rprotocolMajor\x12$\n" +
	"\rprotocolMinor\x18\x03 \x02(\rR\rprotocolMinor\x12\x1a\n" +
	"\btunnelId\x18\x04 \x02(\fR\btunnelId\x12\x1c\n" +
	"\tsignature\x18\x05 \x02(\tR\tsignature\"2\n" +
	"\bProperty\x12\x10\n" +
	"\x03key\x18\x01 \x02(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x02(\tR\x05value\"\x89\x01\n" +
	"\x0fProtocolVersion\x12\x14\n" +
	"\x05magic\x18\x01 \x02(\aR\x05magic\x12\x14\n" +
	"\x05major\x18\x02 \x02(\rR\x05major\x12\x14\n" +
	"\x05minor\x18\x03 \x02(\rR\x05minor\x124\n" +
	"\n" +
	"properties\x18\x04 \x03(\v2\x14.sdgcontrol.PropertyR\n" +
	"properties\".\n" +
	"\x04Ping\x12\x10\n" +
	"\x03seq\x18\x01 \x02(\rR\x03seq\x12\x14\n" +
	"\x05delay\x18\x02 \x01(\rR\x05delay\"\x18\n" +
	"\x04Pong\x12\x10\n" +
	"\x03seq\x18\x01 \x02(\rR\x03seq\",\n" +
	"\fForwardReply\x12\x1c\n" +
	"\tsignature\x18\x01 \x02(\tR\tsignature\"\"\n" +
	"\fForwardError\x12\x12\n" +
	"\x04code\x18\x01 \x02(\rR\x04code\"S\n" +
	"\rConnectToPeer\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\rR\x02id\x12\x16\n" +
	"\x06peerId\x18\x02 \x02(\tR\x06peerId\x12\x1a\n" +
	"\bprotocol\x18\x03 \x02(\tR\bprotocol\"\xaf\x01\n" +
	"\bPeerInfo\x12\x16\n" +
	"\x06peerId\x18\x03 \x02(\tR\x06peerId\x128\n" +
	"\x06server\x18\x04 \x02(\v2 .sdgcontrol.PeerInfo.ForwardHostR\x06server\x12\x1a\n" +
	"\btunnelId\x18\x05 \x02(\fR\btunnelId\x1a5\n" +
	"\vForwardHost\x12\x12\n" +
	"\x04host\x18\x01 \x02(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x02(\rR\x04port\"]\n" +
	"\tPeerReply\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\rR\x02id\x12\x16\n" +
	"\x06result\x18\x02 \x02(\rR\x06result\x12(\n" +
	"\x04peer\x18\x03 \x01(\v2\x14.sdgcontrol.PeerInfoR\x04peer\"d\n" +
	"\fIncomingCall\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\rR\x02id\x12(\n" +
	"\x04peer\x18\x02 \x02(\v2\x14.sdgcontrol.PeerInfoR\x04peer\x12\x1a\n" +
	"\bprotocol\x18\x03 \x02(\tR\bprotocol\";\n" +
	"\x11IncomingCallReply\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\rR\x02id\x12\x16\n" +
	"\x06result\x18\x02 \x02(\rR\x06result\".\n" +
	"\n" +
	"PairRemote\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\rR\x02id\x12\x10\n" +
	"\x03otp\x18\x02 \x02(\tR\x03otpB.Z,github.com/borje/frameo/internal/sdg/control"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)))
	})
	return file_control_proto_rawDescData
}

var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_control_proto_goTypes = []any{
	(*ForwardRemote)(nil),        // 0: sdgcontrol.ForwardRemote
	(*Property)(nil),             // 1: sdgcontrol.Property
	(*ProtocolVersion)(nil),      // 2: sdgcontrol.ProtocolVersion
	(*Ping)(nil),                 // 3: sdgcontrol.Ping
	(*Pong)(nil),                 // 4: sdgcontrol.Pong
	(*ForwardReply)(nil),         // 5: sdgcontrol.ForwardReply
	(*ForwardError)(nil),         // 6: sdgcontrol.ForwardError
	(*ConnectToPeer)(nil),        // 7: sdgcontrol.ConnectToPeer
	(*PeerInfo)(nil),             // 8: sdgcontrol.PeerInfo
	(*PeerReply)(nil),            // 9: sdgcontrol.PeerReply
	(*IncomingCall)(nil),         // 10: sdgcontrol.IncomingCall
	(*IncomingCallReply)(nil),    // 11: sdgcontrol.IncomingCallReply
	(*PairRemote)(nil),           // 12: sdgcontrol.PairRemote
	(*PeerInfo_ForwardHost)(nil), // 13: sdgcontrol.PeerInfo.ForwardHost
}
var file_control_proto_depIdxs = []int32{
	1,  // 0: sdgcontrol.ProtocolVersion.properties:type_name -> sdgcontrol.Property
	13, // 1: sdgcontrol.PeerInfo.server:type_name -> sdgcontrol.PeerInfo.ForwardHost
	8,  // 2: sdgcontrol.PeerReply.peer:type_name -> sdgcontrol.PeerInfo
	8,  // 3: sdgcontrol.IncomingCall.peer:type_name -> sdgcontrol.PeerInfo
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
